### PR TITLE
Add controllers for urls and redirect

### PR DESCRIPTION
**Pull request by luv2144**

### CODE REVIEW

**Comment by d15hw45h3r** [comment]
why can't you use 1 controller for urls and redirect?

**Comment by SaparovSanjar** [comment]
> why can't you use 1 controller for urls and redirect?

good question, I'm interested too

**Comment by luv2144** [comment]
as I could see from the micronaut documentation, there was a separate controller for each endpoint. in this case we need to implement controller for both /r and /urls that's why I splitted them

**Comment by d15hw45h3r** [comment]
> as I could see from the micronaut documentation, there was a separate controller for each endpoint. in this case we need to implement controller for both /r and /urls that's why I splitted them

Okay, I see

**Review by d15hw45h3r — APPROVED** [review]

**Comment by SaparovSanjar** [comment]
> _No description provided._

why can't you pass checkstyle?

**Comment by luv2144** [comment]
honestly, I had no luck to configure checkstyle in my ide, so that I had to fix checkstyle several times. following best practices are nice but sometimes it takes additional efforts

**Pull request merged**
